### ISSUE TITLE
adding saccer3 to the genome list

### ISSUE THREAD

**Issue by frymor** [biocore-ntnu/epic#59]
I was trying to add my own genome to the genome list as explained in the scripts folder. 
It was not a problem to create the environment and install the needed packages.
After starting it and running the dry-run, I get the following error though

```
snakemake -n -s genome.snakefile
Traceback (most recent call last):
  File "/home/yeroslaviz/anaconda_ete/envs/effective-genome-size/bin/snakemake", line 4, in <module>
    import snakemake
  File "/home/yeroslaviz/anaconda_ete/envs/effective-genome-size/lib/python3.5/site-packages/snakemake/__init__.py", line 20, in <module>
    from snakemake.workflow import Workflow
  File "/home/yeroslaviz/anaconda_ete/envs/effective-genome-size/lib/python3.5/site-packages/snakemake/workflow.py", line 23, in <module>
    from snakemake.dag import DAG
  File "/home/yeroslaviz/anaconda_ete/envs/effective-genome-size/lib/python3.5/site-packages/snakemake/dag.py", line 20, in <module>
    from snakemake.jobs import Job, Reason
  File "/home/yeroslaviz/anaconda_ete/envs/effective-genome-size/lib/python3.5/site-packages/snakemake/jobs.py", line 17, in <module>
    from urllib.request import urlopen
  File "/home/yeroslaviz/anaconda_ete/envs/effective-genome-size/lib/python3.5/urllib/request.py", line 88, in <module>
    import http.client
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/http/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

Is it some conflict of the two python version I have?

Thanks
Assa

**Comment by frymor** [comment]
To solve the problem one needs to unset the ```PYTHONPATH```

```
unset PYTHONPATH
```

and hope that the installation of python2.7 will still run afterwards

**Comment by endrebak** [comment]
Thanks. I honestly could not understand this error.

**Comment by endrebak** [comment]
Btw, I have started running epic-effective for all the genomes in UCSC, but it will take weeks I am sure :)

**Comment by frymor** [comment]
this is good, but I think it will be also a good idea not to restrict the usage to only UCSC genomes, as a lot of people are using the Ensembl annotations. 

the fasta files from ensembl are all in a similar structure
```
ftp://ftp.ensembl.org/pub/release-*/fasta/ORGANISM/dna/ORGANISM.GENOME-BUILD.dna.toplevel.fa.gz```

I guess it is a lot of work to add them too, but it would be nice :-)

Otherwise, maybe creating a folder, where the ```chromsize``` files can be saved and read from the epic tool

**Comment by endrebak** [comment]
There is one: https://github.com/biocore-ntnu/epic/tree/master/epic/scripts/chromsizes

I also need an effective genome size for each of those though.

0.2.1 out in bioconda now btw.

**Comment by frymor** [comment]
But If I understood the script correctly, you can calculate the egf from the chromsize file.

Yes i am running it now.

**Comment by endrebak** [comment]
No egf is calculated using the fasta :)
