### ISSUE TITLE
epic-merge throws an error of ValueError: Cannot convert NA to integer

### ISSUE THREAD

**Issue by lucacozzuto** [biocore-ntnu/epic#79]
Dear developers,
I tried to run epic-merge using two matrices and bed files generated by epic and I got the following error:
```
/users/bi/lcozzuto/.pyenv/versions/2.7.13/lib/python2.7/site-packages/numpy/lib/arraysetops.py:463: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
Calling H3K27me3_EWS-FLI_matrix.txt.gz Enriched_H3K27me3_EWS-FLI_matrix.txt.gz in matrix file. (File: merge, Log level: INFO, Time: Tue, 26 Jun 2018 16:19:28 )
Calling H3K27me3_hMSC_matrix.txt.gz Enriched_H3K27me3_hMSC_matrix.txt.gz in matrix file. (File: merge, Log level: INFO, Time: Tue, 26 Jun 2018 16:19:56 )
Traceback (most recent call last):
  File "/users/bi/lcozzuto/.pyenv/versions/2.7.13/bin/epic-merge", line 91, in <module>
    merged_df = main(files, regions, keep_nonenriched, enriched_per_file, nb_cpus)
  File "/users/bi/lcozzuto/.pyenv/versions/2.7.13/lib/python2.7/site-packages/epic/merge/merge.py", line 20, in main
    bin_size = compute_bin_size(dfs)
  File "/users/bi/lcozzuto/.pyenv/versions/2.7.13/lib/python2.7/site-packages/epic/merge/merge_helpers.py", line 20, in compute_bin_size
    bins = df.head(100000).index.get_level_values("Bin").astype(int)
  File "/users/bi/lcozzuto/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pandas/core/indexes/numeric.py", line 318, in astype
    raise ValueError('Cannot convert NA to integer')
ValueError: Cannot convert NA to integer
```

I'm using epic 0.2.9

Best,
Luca

**Comment by endrebak** [comment]
Thanks for reporting btw.

**Comment by lucacozzuto** [comment]
Hi, I was not able to replicate the problem so you can close it.

Thanks!

L
