### ISSUE TITLE
epic and conda

### ISSUE THREAD

**Issue by nservant** [biocore-ntnu/epic#80]
Hi,
I'm trying to use the epic conda environment, but have an issue with scioy.
I can reproduce the error by simply importing the epic function into the python in the conda environment.
Not sure why it seems to use my scipy in local ...
Any idea would be very useful.
Thanks
Nicolas

```
>>python
Python 2.7.15 | packaged by conda-forge | (default, May  8 2018, 14:46:53) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> from epic.run.run_epic import run_epic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/bioinfo/local/build/Centos/envs_conda/epic_0.2.9/lib/python2.7/site-packages/epic/run/run_epic.py", line 25, in <module>
    from epic.statistics.compute_background_probabilites import compute_background_probabilities
  File "/bioinfo/local/build/Centos/envs_conda/epic_0.2.9/lib/python2.7/site-packages/epic/statistics/compute_background_probabilites.py", line 15, in <module>
    from epic.statistics.compute_values_needed_for_recurrence import (
  File "/bioinfo/local/build/Centos/envs_conda/epic_0.2.9/lib/python2.7/site-packages/epic/statistics/compute_values_needed_for_recurrence.py", line 2, in <module>
    from scipy.stats import poisson
  File "/data/users/nservant/.local/lib/python2.7/site-packages/scipy/stats/__init__.py", line 338, in <module>
    from .stats import *
  File "/data/users/nservant/.local/lib/python2.7/site-packages/scipy/stats/stats.py", line 184, in <module>
    import scipy.special as special
  File "/data/users/nservant/.local/lib/python2.7/site-packages/scipy/special/__init__.py", line 586, in <module>
    from ._ufuncs import *
ImportError: liblapack.so.3gf: cannot open shared object file: No such file or directory
>>> 
(/bioinfo/local/build/Centos/envs_conda/epic_0.2.9) 

```

**Comment by endrebak** [comment]
You are missing some linear algebra library? I think google would be of more help, this is stuff beneath, pandas, numpy, all the way down in C-land.

**Comment by nservant** [comment]
indeed it was an issue in my python libs. Fixed.
