### ISSUE TITLE
cannot recognize genome

### ISSUE THREAD

**Issue by Wangcn81** [biocore-ntnu/epic#83]
Hi,

The program does not recognize the genome speTri2 with the -gn option, although it is on your genome list.
Thanks.

**Comment by endrebak** [comment]
What is the error message?

**Comment by endrebak** [comment]
Thanks for reporting btw. Both the chromsizes and egs' are included for speTri2 so I do not understand what the problem might be.

**Comment by Wangcn81** [comment]
Genome speTri2 not found.
 These are the available genomes: ailMel1
anoCar2
aplCal1
aquChr2
balAcu1
braFlo1
calJac1
calJac3
cavPor3
ce10
ce11
cerSim1
chlSab2
chrPic1
danRer10
danRer3
danRer4
danRer5
danRer6
danRer7
dm3
dm6
echTel2
equCab1
equCab2
eriEur1
eriEur2
fr1
fr2
galVar1
gasAcu1
geoFor1
gorGor3
gorGor4
gorGor5
hetGla1
hetGla2
hg18
hg19
hg38
macEug2
melGal1
melGal5
micMur2
mm10
mm9
monDom4
monDom5
myoLuc2
nanPar1
nasLar1
nomLeu1
nomLeu2
nomLeu3
ochPri3
oreNil2
ornAna1
ornAna2
oryCun2
oryLat2
oviAri1
oviAri3
petMar1
petMar2
ponAbe2
priPac1
rheMac2
rheMac3
rheMac8
rhiRox1
rn4
rn5
rn6
sacCer1
sacCer2
sacCer3
saiBol1
sorAra2
speTri2
strPur1
strPur2
susScr2
susScr3
taeGut1
taeGut2
tarSyr2
tetNig1
tetNig2
triMan1
xenTro3
xenTro7
If yours is not there, please request it at github.com/endrebak/epic . (File: genomes, Log level: ERROR, Time: Tue, 14 Aug 2018 10:42:49 )
Traceback (most recent call last):
  File "/data/wangcn/conda/bin/epic", line 271, in <module>
    args.genome, closest_readlength)
  File "/data/wangcn/conda/lib/python3.6/site-packages/epic/config/genomes.py", line 79, in get_effective_genome_length
    logging.info("Using an effective genome fraction of {}.".format(egf))
UnboundLocalError: local variable 'egf' referenced before assignment

**Comment by endrebak** [comment]
Strange. Will look into next week. Does lowercase spetri2 work?
