### ISSUE TITLE
Epic-effective: TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by aboyd003** [biocore-ntnu/epic#91]
Hi. I am attempting to use epic effective to estimate the genome size of a custom assembly for a eukaryotic microbe prior to peak calling. 
`time epic-effective -r 75 /rhome/aboyd003/bigdata/oldGenome/Pinfestans.fa`

I receive the following error: 
`Traceback (most recent call last):
  File "/rhome/aboyd003/.conda/envs/BIOEPIC/bin/epic-effective", line 4, in <module>
    __import__('pkg_resources').run_script('bioepic==0.1.6', 'epic-effective')
  File "/rhome/aboyd003/.conda/envs/BIOEPIC/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/rhome/aboyd003/.conda/envs/BIOEPIC/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/rhome/aboyd003/.conda/envs/BIOEPIC/lib/python2.7/site-packages/bioepic-0.1.6-py2.7.egg-info/scripts/epic-effective", line 35, in <module>
    effective_genome_size(fasta, read_length, nb_cpu, tmpdir)
  File "/rhome/aboyd003/.conda/envs/BIOEPIC/lib/python2.7/site-packages/epic/scripts/effective_genome_size.py", line 22, in effective_genome_size
    logging.info("Temporary directory: " + tmpdir)
TypeError: cannot concatenate 'str' and 'NoneType' objects

real	0m0.766s
user	0m0.332s
sys	0m0.079s`

Sample of definition lines from genome file are provided below. The sequences include Ns.
>7000000037419696
>7000000037419352
>7000000037419663
>7000000037419515

**Comment by endrebak** [comment]
Thanks for trying epic-effective and reporting this bug.

Can you please try setting the `--tmpdir` explicitly?

Like `time epic-effective -r 75 /rhome/aboyd003/bigdata/oldGenome/Pinfestans.fa -t /tmp/`.

**Comment by aboyd003** [comment]
Thank you for your reply. 

I have followed your suggestion and tried running with the temp directory explicitly declared on the command line `time epic-effective -r 75 /rhome/aboyd003/bigdata/oldGenome/Pinfestans.fa -t /rhome/aboyd003/bigdata/oldGenome/tmp/` and declaring it in the function definition `effective_genome_size(fasta, read_length, nb_cores, tmpdir="/rhome/aboyd003/bigdata/oldGenome/tmp/"`. Both methods result in a different error `Failed to open input file '/rhome/aboyd003/bigdata/oldGenome/tmp/Pinfestans.fa.jf'`
indicating some issue with my usage and line 44 of effective_genome_size.py:  
`output_file = os.path.join(tmpdir, '{1}.jf'.format(read_length,                                               basename(fasta)))`

Do you have any ideas of how to troubleshoot this?

**Comment by endrebak** [comment]
No, it has been so long since I used/wrote it, unfortunately. epic is no longer maintained :/ I should really archive this repo.

**Comment by aboyd003** [comment]
No worries. I cannibalized the line for jellyfish and manually did the calculations.

**Comment by endrebak** [comment]
Wonderful! My PhD money runs out soon, otherwise I'd normally try to help :)
